channels:
- conda-forge
dependencies:
- atomistics =0.2.4
- lammps =2024.06.27=*_openmpi_*
- iprpy-data
- pyironflow =0.0.16
- pyiron_workflow =0.12.1
- python =3.12
- pylammpsmpi =0.2.31
- jinja2 =3.1.6
- pandas =2.2.3
- pyiron_lammps =0.4.0
